// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQZfxRW0jgme4THdlP6zc962f0Ju7bdo',
    appId: '1:816258150287:web:6e3f14df4349a087c8e5fa',
    messagingSenderId: '816258150287',
    projectId: 'mindmate-76e5c',
    authDomain: 'mindmate-76e5c.firebaseapp.com',
    storageBucket: 'mindmate-76e5c.firebasestorage.app',
    measurementId: 'G-SSG26S6CFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzqlxNATy-lnspp7lRmsPlkK_RATfKtbs',
    appId: '1:816258150287:android:efd10e9b068369e6c8e5fa',
    messagingSenderId: '816258150287',
    projectId: 'mindmate-76e5c',
    storageBucket: 'mindmate-76e5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjkuLRj8lrtvDOatgzKOChPA0kIBzps0',
    appId: '1:816258150287:ios:dfde1bc012db5fc8c8e5fa',
    messagingSenderId: '816258150287',
    projectId: 'mindmate-76e5c',
    storageBucket: 'mindmate-76e5c.firebasestorage.app',
    iosBundleId: 'com.example.mindmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkjkuLRj8lrtvDOatgzKOChPA0kIBzps0',
    appId: '1:816258150287:ios:dfde1bc012db5fc8c8e5fa',
    messagingSenderId: '816258150287',
    projectId: 'mindmate-76e5c',
    storageBucket: 'mindmate-76e5c.firebasestorage.app',
    iosBundleId: 'com.example.mindmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPQZfxRW0jgme4THdlP6zc962f0Ju7bdo',
    appId: '1:816258150287:web:25e049915c55015ac8e5fa',
    messagingSenderId: '816258150287',
    projectId: 'mindmate-76e5c',
    authDomain: 'mindmate-76e5c.firebaseapp.com',
    storageBucket: 'mindmate-76e5c.firebasestorage.app',
    measurementId: 'G-Y9Y661LG4T',
  );

}